name: CI Pipeline

on:
  push:
    branches:
      - main
      - posterv2
  pull_request:
    branches:
      - main
      - posterv2

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements-dev.txt

      - name: Install gdown to download models
        run: pip install gdown
      - name: Download ir50.pth from Google Drive
        run: |
          gdown https://drive.google.com/uc?id=12QjP4CJOzNn7j4AkfNfODXpwRpu5O9ZT -O fer/posterv2/pretrain/ir50.pth
      - name: Download mobilefacenet_model_best.pth.tar from Google Drive
        run: |
          gdown https://drive.google.com/uc?id=1oMGcEyhqQLjaca4pppEYV8xONmXU6ucv -O fer/posterv2/pretrain/mobilefacenet_model_best.pth.tar
      - name: Download affectnet-7-model_best_state_dict_only.pth from Google Drive
        run: |
          gdown https://drive.google.com/uc?id=10NWqIcEAHjScAGlCKryEpWgiKJvyVlaF -O fer/posterv2/pretrain/affectnet-7-model_best_state_dict_only.pth      

      - name: Run Tests
        run: pytest

  build-and-test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t fer-ms .

      - name: Run Docker Container
        run: docker run -d -p 8000:8000 fer-ms

      - name: Wait for API to be ready
        run: sleep 10

      - name: Test API with curl
        run: curl -X GET http://localhost:8000/ping
